<a href="https://colab.research.google.com/github/fornieligulo/NBC-SETELAH-SIDANG/blob/main/Cleanning_Data_SETELAH_SIDANG_TweetInggris_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Labrary dan Read Dataset**

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
import nltk 
import string
import re

In [22]:
# Load dataset
def load_data():
    data = pd.read_csv('DataSetelahSidang-Selection.csv')
    return data

tweet_df = load_data()
tweet_df.head()

,created_at,date,time,username,tweet,language
0,2023-02-13 22:39:53 SE Asia Standard Time,13/02/2023,22:39:53,_suwek_,"Yuk pak hakim Wahyu Imam Santoso, Morgan Siman...",in
1,2023-02-13 22:06:19 SE Asia Standard Time,13/02/2023,22:06:19,dolphino_14,@KompasTV Kuat Ma'ruf dan Ricky Rizal bisa jad...,in
2,2023-02-13 21:20:15 SE Asia Standard Time,13/02/2023,21:20:15,kompastv,Jangan lewatkan BREAKING NEWS - Sidang Vonis R...,in
3,2023-02-13 21:18:37 SE Asia Standard Time,13/02/2023,21:18:37,kompastv,Apakah Majelis Hakim akan memberikan vonis leb...,in
4,2023-02-13 20:56:11 SE Asia Standard Time,13/02/2023,20:56:11,kompastv,Siapkah Sahabat KompasTV mendengar putusan sid...,in

In [23]:
#definisi dataframe
#ubah dataframe sesuai column kalian
df  = pd.DataFrame(tweet_df[['created_at','language', 'date', 'time', 'username', 'tweet']])
df

,created_at,language,date,time,username,tweet
0,2023-02-13 22:39:53 SE Asia Standard Time,in,13/02/2023,22:39:53,_suwek_,"Yuk pak hakim Wahyu Imam Santoso, Morgan Siman..."
1,2023-02-13 22:06:19 SE Asia Standard Time,in,13/02/2023,22:06:19,dolphino_14,@KompasTV Kuat Ma'ruf dan Ricky Rizal bisa jad...
2,2023-02-13 21:20:15 SE Asia Standard Time,in,13/02/2023,21:20:15,kompastv,Jangan lewatkan BREAKING NEWS - Sidang Vonis R...
3,2023-02-13 21:18:37 SE Asia Standard Time,in,13/02/2023,21:18:37,kompastv,Apakah Majelis Hakim akan memberikan vonis leb...
4,2023-02-13 20:56:11 SE Asia Standard Time,in,13/02/2023,20:56:11,kompastv,Siapkah Sahabat KompasTV mendengar putusan sid...
...,...,...,...,...,...,...
5105,2023-03-08 00:09:02 SE Asia Standard Time,in,08/03/2023,0:09:02,ekoajo8,@mulkanjabariyan Buku itu terlihat rapi lukisa...
5106,2023-03-08 00:08:27 SE Asia Standard Time,in,08/03/2023,0:08:27,teuku_hazbi,@adhiyanblog @henrysubiakto Ini baru jawaban y...
5107,2023-03-08 00:06:29 SE Asia Standard Time,in,08/03/2023,0:06:29,kokoronotomo911,@SantorinisSun Eyang Seto dah siuman krna kmar...
5108,2023-03-08 00:03:20 SE Asia Standard Time,in,08/03/2023,0:03:20,sentenfebrari10,@WagimanDeep212_ Kalau bahaya kt mengkritik po...
5109,2023-03-08 00:00:36 SE Asia Standard Time,in,08/03/2023,0:00:36,tvonenews,"Curhat di Medsos, Trisha Eungelica, Putri Sulu..."

# **Proses Cleaning Data**

In [24]:
#remove user
def remove_pattern(input_txt, pattern):
    r = re.findall(pattern, input_txt)
    for i in r:
        input_txt = re.sub(i, '', input_txt)
    return input_txt    
df['remove_user'] = np.vectorize(remove_pattern)(df['tweet'], "@[\w]*")

In [25]:
df

,created_at,language,date,time,username,tweet,remove_user
0,2023-02-13 22:39:53 SE Asia Standard Time,in,13/02/2023,22:39:53,_suwek_,"Yuk pak hakim Wahyu Imam Santoso, Morgan Siman...","Yuk pak hakim Wahyu Imam Santoso, Morgan Siman..."
1,2023-02-13 22:06:19 SE Asia Standard Time,in,13/02/2023,22:06:19,dolphino_14,@KompasTV Kuat Ma'ruf dan Ricky Rizal bisa jad...,Kuat Ma'ruf dan Ricky Rizal bisa jadi kembar ...
2,2023-02-13 21:20:15 SE Asia Standard Time,in,13/02/2023,21:20:15,kompastv,Jangan lewatkan BREAKING NEWS - Sidang Vonis R...,Jangan lewatkan BREAKING NEWS - Sidang Vonis R...
3,2023-02-13 21:18:37 SE Asia Standard Time,in,13/02/2023,21:18:37,kompastv,Apakah Majelis Hakim akan memberikan vonis leb...,Apakah Majelis Hakim akan memberikan vonis leb...
4,2023-02-13 20:56:11 SE Asia Standard Time,in,13/02/2023,20:56:11,kompastv,Siapkah Sahabat KompasTV mendengar putusan sid...,Siapkah Sahabat KompasTV mendengar putusan sid...
...,...,...,...,...,...,...,...
5105,2023-03-08 00:09:02 SE Asia Standard Time,in,08/03/2023,0:09:02,ekoajo8,@mulkanjabariyan Buku itu terlihat rapi lukisa...,Buku itu terlihat rapi lukisan tidak terlihat...
5106,2023-03-08 00:08:27 SE Asia Standard Time,in,08/03/2023,0:08:27,teuku_hazbi,@adhiyanblog @henrysubiakto Ini baru jawaban y...,"Ini baru jawaban yang tepat ,"
5107,2023-03-08 00:06:29 SE Asia Standard Time,in,08/03/2023,0:06:29,kokoronotomo911,@SantorinisSun Eyang Seto dah siuman krna kmar...,Eyang Seto dah siuman krna kmaren ditolak sam...
5108,2023-03-08 00:03:20 SE Asia Standard Time,in,08/03/2023,0:03:20,sentenfebrari10,@WagimanDeep212_ Kalau bahaya kt mengkritik po...,"Kalau bahaya kt mengkritik polisi,, jangan bu..."
5109,2023-03-08 00:00:36 SE Asia Standard Time,in,08/03/2023,0:00:36,tvonenews,"Curhat di Medsos, Trisha Eungelica, Putri Sulu...","Curhat di Medsos, Trisha Eungelica, Putri Sulu..."

In [26]:
def remove(tweet):
    #remove angka
    tweet = re.sub('[0-9]+', '', tweet)
    
    # remove stock market tickers like $GE
    tweet = re.sub(r'\$\w*', '', tweet)
 
    # remove old style retweet text "RT"
    tweet = re.sub(r'^RT[\s]+', '', tweet)
    
    # remove hashtags
    # only removing the hash # sign from the word
    tweet = re.sub(r'#', '', tweet)
    return tweet
df['remove_http'] = df['remove_user'].apply(lambda x: remove(x))

In [27]:
df

,created_at,language,date,time,username,tweet,remove_user,remove_http
0,2023-02-13 22:39:53 SE Asia Standard Time,in,13/02/2023,22:39:53,_suwek_,"Yuk pak hakim Wahyu Imam Santoso, Morgan Siman...","Yuk pak hakim Wahyu Imam Santoso, Morgan Siman...","Yuk pak hakim Wahyu Imam Santoso, Morgan Siman..."
1,2023-02-13 22:06:19 SE Asia Standard Time,in,13/02/2023,22:06:19,dolphino_14,@KompasTV Kuat Ma'ruf dan Ricky Rizal bisa jad...,Kuat Ma'ruf dan Ricky Rizal bisa jadi kembar ...,Kuat Ma'ruf dan Ricky Rizal bisa jadi kembar ...
2,2023-02-13 21:20:15 SE Asia Standard Time,in,13/02/2023,21:20:15,kompastv,Jangan lewatkan BREAKING NEWS - Sidang Vonis R...,Jangan lewatkan BREAKING NEWS - Sidang Vonis R...,Jangan lewatkan BREAKING NEWS - Sidang Vonis R...
3,2023-02-13 21:18:37 SE Asia Standard Time,in,13/02/2023,21:18:37,kompastv,Apakah Majelis Hakim akan memberikan vonis leb...,Apakah Majelis Hakim akan memberikan vonis leb...,Apakah Majelis Hakim akan memberikan vonis leb...
4,2023-02-13 20:56:11 SE Asia Standard Time,in,13/02/2023,20:56:11,kompastv,Siapkah Sahabat KompasTV mendengar putusan sid...,Siapkah Sahabat KompasTV mendengar putusan sid...,Siapkah Sahabat KompasTV mendengar putusan sid...
...,...,...,...,...,...,...,...,...
5105,2023-03-08 00:09:02 SE Asia Standard Time,in,08/03/2023,0:09:02,ekoajo8,@mulkanjabariyan Buku itu terlihat rapi lukisa...,Buku itu terlihat rapi lukisan tidak terlihat...,Buku itu terlihat rapi lukisan tidak terlihat...
5106,2023-03-08 00:08:27 SE Asia Standard Time,in,08/03/2023,0:08:27,teuku_hazbi,@adhiyanblog @henrysubiakto Ini baru jawaban y...,"Ini baru jawaban yang tepat ,","Ini baru jawaban yang tepat ,"
5107,2023-03-08 00:06:29 SE Asia Standard Time,in,08/03/2023,0:06:29,kokoronotomo911,@SantorinisSun Eyang Seto dah siuman krna kmar...,Eyang Seto dah siuman krna kmaren ditolak sam...,Eyang Seto dah siuman krna kmaren ditolak sam...
5108,2023-03-08 00:03:20 SE Asia Standard Time,in,08/03/2023,0:03:20,sentenfebrari10,@WagimanDeep212_ Kalau bahaya kt mengkritik po...,"Kalau bahaya kt mengkritik polisi,, jangan bu...","Kalau bahaya kt mengkritik polisi,, jangan bu..."
5109,2023-03-08 00:00:36 SE Asia Standard Time,in,08/03/2023,0:00:36,tvonenews,"Curhat di Medsos, Trisha Eungelica, Putri Sulu...","Curhat di Medsos, Trisha Eungelica, Putri Sulu...","Curhat di Medsos, Trisha Eungelica, Putri Sulu..."

In [28]:
#Remove file dup
df.sort_values("remove_http", inplace = True)
df.drop_duplicates(subset ="remove_http", keep = 'first', inplace = True)

In [29]:
df

,created_at,language,date,time,username,tweet,remove_user,remove_http
4126,2023-02-28 18:26:14 SE Asia Standard Time,in,28/02/2023,18:26:14,politikmulu,@Obyfabianeros @YaqutCQoumas @NenkMonica @IMCM...,Bocah baru hidup kemaren aja so...,Bocah baru hidup kemaren aja so...
1377,2023-02-20 07:50:55 SE Asia Standard Time,in,20/02/2023,7:50:55,nsttroby,@Miduk17 @PolitikKantor @KomikSelow @YRadianto...,Duh. Kok pansos hotman paris ud...,Duh. Kok pansos hotman paris ud...
335,2023-02-16 23:31:00 SE Asia Standard Time,in,16/02/2023,23:31:00,andaretos37,@kakangprabu007 @ListyoSigitP @didienAZHAR @Ip...,Hukum publik merusak dasar huku...,Hukum publik merusak dasar huku...
4320,2023-03-01 00:48:02 SE Asia Standard Time,in,01/03/2023,0:48:02,zandaclause,@BismaBara @CCICPolri @Gojekmilitan @NenkMonic...,Waaah mainannya kayak sambo sam...,Waaah mainannya kayak sambo sam...
3309,2023-02-24 13:33:20 SE Asia Standard Time,in,24/02/2023,13:33:20,hagj12,@BismaBara @ListyoSigitP @NenkMonica @IMCMushr...,gw paham Bharada E sdh membantu...,gw paham Bharada E sdh membantu...
...,...,...,...,...,...,...,...,...
199,2023-02-14 09:04:31 SE Asia Standard Time,in,14/02/2023,9:04:31,kompascom,🔴LIVE - Sidang Vonis Ricky Rizal dan Kuat Ma'r...,🔴LIVE - Sidang Vonis Ricky Rizal dan Kuat Ma'r...,🔴LIVE - Sidang Vonis Ricky Rizal dan Kuat Ma'r...
833,2023-02-17 00:35:07 SE Asia Standard Time,in,17/02/2023,0:35:07,convomfs,🤍 adiknya mendiang Brigadir J kan post beberap...,🤍 adiknya mendiang Brigadir J kan post beberap...,🤍 adiknya mendiang Brigadir J kan post beberap...
345,2023-02-16 22:55:10 SE Asia Standard Time,in,16/02/2023,22:55:10,convomfs,🤍 beberapa fans richard eliezer kenapa syerem ...,🤍 beberapa fans richard eliezer kenapa syerem ...,🤍 beberapa fans richard eliezer kenapa syerem ...
3527,2023-02-25 16:26:21 SE Asia Standard Time,in,25/02/2023,16:26:21,hoxxynaya,"🦋: Eh, vonis Bharada E dah keluar M (adek sepu...","🦋: Eh, vonis Bharada E dah keluar M (adek sepu...","🦋: Eh, vonis Bharada E dah keluar M (adek sepu..."
4867,2023-03-07 13:40:59 SE Asia Standard Time,in,07/03/2023,13:40:59,raffgamingbuddy,"🧒 : ma, beliin motor dongg 🧕 : mau motor yang ...","🧒 : ma, beliin motor dongg 🧕 : mau motor yang ...","🧒 : ma, beliin motor dongg 🧕 : mau motor yang ..."

In [30]:
#insttal library stopwords
!pip install Sastrawi

from nltk.corpus import stopwords

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: Sastrawi in /usr/local/lib/python3.8/dist-packages (1.0.1)

In [31]:
# Mendownload daftar kata yang ada (vocabulary)
nltk.download('stopwords')
from nltk.corpus import stopwords
 
# Memeriksa daftar kata di stopwords
inggris = stopwords.words('english')
indo = stopwords.words('indonesian')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [32]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
psi = StemmerFactory()
stemmer = psi.create_stemmer()

In [33]:
#import stopword
from nltk.corpus import stopwords 
stopwords_indonesia = stopwords.words('indonesian')
stopwords_english = stopwords.words('english')

In [34]:
#tokenize
from nltk.tokenize import TweetTokenizer

In [35]:
# Happy Emoticons
emoticons_happy = set([
    ':-)', ':)', ';)', ':o)', ':]', ':3', ':c)', ':>', '=]', '8)', '=)', ':}',
    ':^)', ':-D', ':D', '8-D', '8D', 'x-D', 'xD', 'X-D', 'XD', '=-D', '=D',
    '=-3', '=3', ':-))', ":'-)", ":')", ':*', ':^*', '>:P', ':-P', ':P', 'X-P',
    'x-p', 'xp', 'XP', ':-p', ':p', '=p', ':-b', ':b', '>:)', '>;)', '>:-)',
    '<3'
    ])

In [36]:
# Sad Emoticons
emoticons_sad = set([
    ':L', ':-/', '>:/', ':S', '>:[', ':@', ':-(', ':[', ':-||', '=L', ':<',
    ':-[', ':-<', '=\\', '=/', '>:(', ':(', '>.<', ":'-(", ":'(", ':\\', ':-c',
    ':c', ':{', '>:\\', ';('
    ])

In [37]:
# all emoticons (happy + sad)
emoticons = emoticons_happy.union(emoticons_sad)
 
def clean_tweets(tweet):
    # remove stock market tickers like $GE
    tweet = re.sub(r'\$\w*', '', tweet)
 
    # remove old style retweet text "RT"
    tweet = re.sub(r'^RT[\s]+', '', tweet)
 
    # remove hyperlinks
    tweet = re.sub(r'https?:\/\/.*[\r\n]*', '', tweet)
    
    # remove hashtags
    # only removing the hash # sign from the word
    tweet = re.sub(r'#', '', tweet)
    
    #remove coma
    tweet = re.sub(r',','',tweet)
    
    #remove angka
    tweet = re.sub('[0-9]+', '', tweet)
 
    # tokenize tweets
    tokenizer = TweetTokenizer(preserve_case=False, strip_handles=True, reduce_len=True)
    tweet_tokens = tokenizer.tokenize(tweet)
 
    tweets_clean = []    
    for word in tweet_tokens:
        if (word not in stopwords_indonesia and   # remove stopwords
              word not in emoticons and           # remove emoticons
                word not in string.punctuation):  # remove punctuation
            #tweets_clean.append(word)
            stem_word = stemmer.stem(word)        # stemming word
            tweets_clean.append(stem_word)
 
    return tweets_clean
df['tweet_clean'] = df['remove_http'].apply(lambda x: clean_tweets(x))

In [38]:
df

,created_at,language,date,time,username,tweet,remove_user,remove_http,tweet_clean
4126,2023-02-28 18:26:14 SE Asia Standard Time,in,28/02/2023,18:26:14,politikmulu,@Obyfabianeros @YaqutCQoumas @NenkMonica @IMCM...,Bocah baru hidup kemaren aja so...,Bocah baru hidup kemaren aja so...,"[bocah, hidup, kemaren, aja, sok, sok, an, ang..."
1377,2023-02-20 07:50:55 SE Asia Standard Time,in,20/02/2023,7:50:55,nsttroby,@Miduk17 @PolitikKantor @KomikSelow @YRadianto...,Duh. Kok pansos hotman paris ud...,Duh. Kok pansos hotman paris ud...,"[duh, pansos, hotman, paris, udah, beken, haha..."
335,2023-02-16 23:31:00 SE Asia Standard Time,in,16/02/2023,23:31:00,andaretos37,@kakangprabu007 @ListyoSigitP @didienAZHAR @Ip...,Hukum publik merusak dasar huku...,Hukum publik merusak dasar huku...,"[hukum, publik, rusak, dasar, hukum, preseden,..."
4320,2023-03-01 00:48:02 SE Asia Standard Time,in,01/03/2023,0:48:02,zandaclause,@BismaBara @CCICPolri @Gojekmilitan @NenkMonic...,Waaah mainannya kayak sambo sam...,Waaah mainannya kayak sambo sam...,"[waaah, main, kayak, sambo, pc, beneran, nih, ..."
3309,2023-02-24 13:33:20 SE Asia Standard Time,in,24/02/2023,13:33:20,hagj12,@BismaBara @ListyoSigitP @NenkMonica @IMCMushr...,gw paham Bharada E sdh membantu...,gw paham Bharada E sdh membantu...,"[gw, paham, bharada, e, sdh, bantu, sidang, ga..."
...,...,...,...,...,...,...,...,...,...
199,2023-02-14 09:04:31 SE Asia Standard Time,in,14/02/2023,9:04:31,kompascom,🔴LIVE - Sidang Vonis Ricky Rizal dan Kuat Ma'r...,🔴LIVE - Sidang Vonis Ricky Rizal dan Kuat Ma'r...,🔴LIVE - Sidang Vonis Ricky Rizal dan Kuat Ma'r...,"[, live, sidang, vonis, ricky, rizal, kuat, ma..."
833,2023-02-17 00:35:07 SE Asia Standard Time,in,17/02/2023,0:35:07,convomfs,🤍 adiknya mendiang Brigadir J kan post beberap...,🤍 adiknya mendiang Brigadir J kan post beberap...,🤍 adiknya mendiang Brigadir J kan post beberap...,"[, adik, mendiang, brigadir, j, post, foto, gt..."
345,2023-02-16 22:55:10 SE Asia Standard Time,in,16/02/2023,22:55:10,convomfs,🤍 beberapa fans richard eliezer kenapa syerem ...,🤍 beberapa fans richard eliezer kenapa syerem ...,🤍 beberapa fans richard eliezer kenapa syerem ...,"[, fans, richard, eliezer, syerem, bgt, ya, ke..."
3527,2023-02-25 16:26:21 SE Asia Standard Time,in,25/02/2023,16:26:21,hoxxynaya,"🦋: Eh, vonis Bharada E dah keluar M (adek sepu...","🦋: Eh, vonis Bharada E dah keluar M (adek sepu...","🦋: Eh, vonis Bharada E dah keluar M (adek sepu...","[, eh, vonis, bharada, e, dah, m, adek, sepupu..."
4867,2023-03-07 13:40:59 SE Asia Standard Time,in,07/03/2023,13:40:59,raffgamingbuddy,"🧒 : ma, beliin motor dongg 🧕 : mau motor yang ...","🧒 : ma, beliin motor dongg 🧕 : mau motor yang ...","🧒 : ma, beliin motor dongg 🧕 : mau motor yang ...","[, ma, beliin, motor, dongg, , motor, kek, gmn..."

In [39]:
#remove punct
def remove_punct(text):
    text  = " ".join([char for char in text if char not in string.punctuation])
    return text
df['Tweet'] = df['tweet_clean'].apply(lambda x: remove_punct(x))

In [40]:
df

,created_at,language,date,time,username,tweet,remove_user,remove_http,tweet_clean,Tweet
4126,2023-02-28 18:26:14 SE Asia Standard Time,in,28/02/2023,18:26:14,politikmulu,@Obyfabianeros @YaqutCQoumas @NenkMonica @IMCM...,Bocah baru hidup kemaren aja so...,Bocah baru hidup kemaren aja so...,"[bocah, hidup, kemaren, aja, sok, sok, an, ang...",bocah hidup kemaren aja sok sok an angkat isu ...
1377,2023-02-20 07:50:55 SE Asia Standard Time,in,20/02/2023,7:50:55,nsttroby,@Miduk17 @PolitikKantor @KomikSelow @YRadianto...,Duh. Kok pansos hotman paris ud...,Duh. Kok pansos hotman paris ud...,"[duh, pansos, hotman, paris, udah, beken, haha...",duh pansos hotman paris udah beken haha ga tuj...
335,2023-02-16 23:31:00 SE Asia Standard Time,in,16/02/2023,23:31:00,andaretos37,@kakangprabu007 @ListyoSigitP @didienAZHAR @Ip...,Hukum publik merusak dasar huku...,Hukum publik merusak dasar huku...,"[hukum, publik, rusak, dasar, hukum, preseden,...",hukum publik rusak dasar hukum preseden buruk ...
4320,2023-03-01 00:48:02 SE Asia Standard Time,in,01/03/2023,0:48:02,zandaclause,@BismaBara @CCICPolri @Gojekmilitan @NenkMonic...,Waaah mainannya kayak sambo sam...,Waaah mainannya kayak sambo sam...,"[waaah, main, kayak, sambo, pc, beneran, nih, ...",waaah main kayak sambo pc beneran nih yg udah ...
3309,2023-02-24 13:33:20 SE Asia Standard Time,in,24/02/2023,13:33:20,hagj12,@BismaBara @ListyoSigitP @NenkMonica @IMCMushr...,gw paham Bharada E sdh membantu...,gw paham Bharada E sdh membantu...,"[gw, paham, bharada, e, sdh, bantu, sidang, ga...",gw paham bharada e sdh bantu sidang gak gin ka...
...,...,...,...,...,...,...,...,...,...,...
199,2023-02-14 09:04:31 SE Asia Standard Time,in,14/02/2023,9:04:31,kompascom,🔴LIVE - Sidang Vonis Ricky Rizal dan Kuat Ma'r...,🔴LIVE - Sidang Vonis Ricky Rizal dan Kuat Ma'r...,🔴LIVE - Sidang Vonis Ricky Rizal dan Kuat Ma'r...,"[, live, sidang, vonis, ricky, rizal, kuat, ma...",live sidang vonis ricky rizal kuat ma ruf
833,2023-02-17 00:35:07 SE Asia Standard Time,in,17/02/2023,0:35:07,convomfs,🤍 adiknya mendiang Brigadir J kan post beberap...,🤍 adiknya mendiang Brigadir J kan post beberap...,🤍 adiknya mendiang Brigadir J kan post beberap...,"[, adik, mendiang, brigadir, j, post, foto, gt...",adik mendiang brigadir j post foto gtu gue sho...
345,2023-02-16 22:55:10 SE Asia Standard Time,in,16/02/2023,22:55:10,convomfs,🤍 beberapa fans richard eliezer kenapa syerem ...,🤍 beberapa fans richard eliezer kenapa syerem ...,🤍 beberapa fans richard eliezer kenapa syerem ...,"[, fans, richard, eliezer, syerem, bgt, ya, ke...",fans richard eliezer syerem bgt ya keluarga br...
3527,2023-02-25 16:26:21 SE Asia Standard Time,in,25/02/2023,16:26:21,hoxxynaya,"🦋: Eh, vonis Bharada E dah keluar M (adek sepu...","🦋: Eh, vonis Bharada E dah keluar M (adek sepu...","🦋: Eh, vonis Bharada E dah keluar M (adek sepu...","[, eh, vonis, bharada, e, dah, m, adek, sepupu...",eh vonis bharada e dah m adek sepupu kelas sd ...
4867,2023-03-07 13:40:59 SE Asia Standard Time,in,07/03/2023,13:40:59,raffgamingbuddy,"🧒 : ma, beliin motor dongg 🧕 : mau motor yang ...","🧒 : ma, beliin motor dongg 🧕 : mau motor yang ...","🧒 : ma, beliin motor dongg 🧕 : mau motor yang ...","[, ma, beliin, motor, dongg, , motor, kek, gmn...",ma beliin motor dongg motor kek gmn motor samb...

In [41]:
df.sort_values("Tweet", inplace = True)
df

,created_at,language,date,time,username,tweet,remove_user,remove_http,tweet_clean,Tweet
3676,2023-02-26 13:16:17 SE Asia Standard Time,in,26/02/2023,13:16:17,milanoutloud,@JNotobotosongo https://t.co/3YXumQd1FW Sala...,https://t.co/3YXumQd1FW Salah satu syarat J...,https://t.co/YXumQdFW Salah satu syarat JC ...,[],
1522,2023-02-21 14:45:39 SE Asia Standard Time,in,21/02/2023,14:45:39,terasjabar_,https://t.co/qvODeCMCdJ Berstatus Justice Col...,https://t.co/qvODeCMCdJ Berstatus Justice Col...,https://t.co/qvODeCMCdJ Berstatus Justice Col...,[],
366,2023-02-16 21:41:51 SE Asia Standard Time,in,16/02/2023,21:41:51,rafigates,https://t.co/wPAQYn873t Mengenai waktu eksekut...,https://t.co/wPAQYn873t Mengenai waktu eksekut...,https://t.co/wPAQYnt Mengenai waktu eksekuti m...,[],
2918,2023-02-23 09:09:04 SE Asia Standard Time,in,23/02/2023,9:09:04,kaltimberita,https://t.co/g5m9FsJxDI SAMBUTAN Rekan-rekan ...,https://t.co/g5m9FsJxDI SAMBUTAN Rekan-rekan ...,https://t.co/gmFsJxDI SAMBUTAN Rekan-rekan Bh...,[],
930,2023-02-18 16:26:08 SE Asia Standard Time,in,18/02/2023,16:26:08,ratnowistu,https://t.co/dKvge0jeNs : Perjalanan Bharada E...,https://t.co/dKvge0jeNs : Perjalanan Bharada E...,https://t.co/dKvgejeNs : Perjalanan Bharada E ...,[],
...,...,...,...,...,...,...,...,...,...,...
1076,2023-02-19 19:00:15 SE Asia Standard Time,in,19/02/2023,19:00:15,vivacoid,"Yuni Hutabarat, kakak kandung Brigadir J, leb...","Yuni Hutabarat, kakak kandung Brigadir J, leb...","Yuni Hutabarat, kakak kandung Brigadir J, leb...","[yuni, hutabarat, kakak, kandung, brigadir, j,...",yuni hutabarat kakak kandung brigadir j rela r...
5061,2023-03-08 04:38:47 SE Asia Standard Time,in,08/03/2023,4:38:47,danjuma_03,@MuazuJajiSambo Zaka gama Lafiya Barkama,Zaka gama Lafiya Barkama,Zaka gama Lafiya Barkama,"[zaka, gama, lafiya, barkama]",zaka gama lafiya barkama
2818,2023-02-23 11:29:54 SE Asia Standard Time,in,23/02/2023,11:29:54,herjobi,@MustEkeph @KemenkeuRI @DitjenPajakRI @prastow...,Zakheus di masa kini sdh alih profesi mjd ...,Zakheus di masa kini sdh alih profesi mjd ...,"[zakheus, sdh, alih, profesi, mjd, polisi, om,...",zakheus sdh alih profesi mjd polisi om bosen j...
5087,2023-03-08 01:14:51 SE Asia Standard Time,in,08/03/2023,1:14:51,cleopas_sambo,"Zambia ku chalo. Uchi puba watu, onani manje ...","Zambia ku chalo. Uchi puba watu, onani manje ...","Zambia ku chalo. Uchi puba watu, onani manje ...","[zambia, ku, chalo, uchi, puba, watu, onani, m...",zambia ku chalo uchi puba watu onani manje
4720,2023-03-07 16:40:58 SE Asia Standard Time,in,07/03/2023,16:40:58,sadiqsambo5,@Realnoni4Real 2051425661 zenith bank sodiq sambo,2051425661 zenith bank sodiq sambo,zenith bank sodiq sambo,"[zenith, bank, sodiq, sambo]",zenith bank sodiq sambo

In [42]:
df.to_csv('DATA CLEANING-01.csv',encoding='utf8', index=False)

In [43]:
df.drop(df.columns[[5,6,7,8]], axis = 1, inplace = True)
df

,created_at,language,date,time,username,Tweet
3676,2023-02-26 13:16:17 SE Asia Standard Time,in,26/02/2023,13:16:17,milanoutloud,
1522,2023-02-21 14:45:39 SE Asia Standard Time,in,21/02/2023,14:45:39,terasjabar_,
366,2023-02-16 21:41:51 SE Asia Standard Time,in,16/02/2023,21:41:51,rafigates,
2918,2023-02-23 09:09:04 SE Asia Standard Time,in,23/02/2023,9:09:04,kaltimberita,
930,2023-02-18 16:26:08 SE Asia Standard Time,in,18/02/2023,16:26:08,ratnowistu,
...,...,...,...,...,...,...
1076,2023-02-19 19:00:15 SE Asia Standard Time,in,19/02/2023,19:00:15,vivacoid,yuni hutabarat kakak kandung brigadir j rela r...
5061,2023-03-08 04:38:47 SE Asia Standard Time,in,08/03/2023,4:38:47,danjuma_03,zaka gama lafiya barkama
2818,2023-02-23 11:29:54 SE Asia Standard Time,in,23/02/2023,11:29:54,herjobi,zakheus sdh alih profesi mjd polisi om bosen j...
5087,2023-03-08 01:14:51 SE Asia Standard Time,in,08/03/2023,1:14:51,cleopas_sambo,zambia ku chalo uchi puba watu onani manje
4720,2023-03-07 16:40:58 SE Asia Standard Time,in,07/03/2023,16:40:58,sadiqsambo5,zenith bank sodiq sambo

In [44]:
df.drop_duplicates(subset ="Tweet", keep = 'first', inplace = True)
df

,created_at,language,date,time,username,Tweet
3676,2023-02-26 13:16:17 SE Asia Standard Time,in,26/02/2023,13:16:17,milanoutloud,
4844,2023-03-07 14:04:58 SE Asia Standard Time,in,07/03/2023,14:04:58,mg_sambo_,aaatoh ai shineh bayan
430,2023-02-16 18:34:39 SE Asia Standard Time,in,16/02/2023,18:34:39,meeemeeeaaa,aamiin ichad anak anggap keluarga alm brigadir...
4825,2023-03-07 14:33:31 SE Asia Standard Time,in,07/03/2023,14:33:31,kalasambo,aamiin serius pokok
5048,2023-03-08 06:03:06 SE Asia Standard Time,in,08/03/2023,6:03:06,julaaaaak,abdi pajak
...,...,...,...,...,...,...
1076,2023-02-19 19:00:15 SE Asia Standard Time,in,19/02/2023,19:00:15,vivacoid,yuni hutabarat kakak kandung brigadir j rela r...
5061,2023-03-08 04:38:47 SE Asia Standard Time,in,08/03/2023,4:38:47,danjuma_03,zaka gama lafiya barkama
2818,2023-02-23 11:29:54 SE Asia Standard Time,in,23/02/2023,11:29:54,herjobi,zakheus sdh alih profesi mjd polisi om bosen j...
5087,2023-03-08 01:14:51 SE Asia Standard Time,in,08/03/2023,1:14:51,cleopas_sambo,zambia ku chalo uchi puba watu onani manje
4720,2023-03-07 16:40:58 SE Asia Standard Time,in,07/03/2023,16:40:58,sadiqsambo5,zenith bank sodiq sambo

In [45]:
df.to_csv('DATA CLEANING-02.csv',encoding='utf8', index=False)